chore(helm-checks): add simple-data-backend
eclipse-tractusx/tractus-x-umbrella pull request #59
Opened 2024-03-21 16:31 UTC by evegufy

## Description

chore(helm-checks): add simple-data-backend

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-03-22 10:15 UTC, ds-jhartmann requested changes

2024-03-22 10:15 UTC, ds-jhartmann commented on .github/workflows/helm-checks.yaml
> +        context: .
```suggestion
        context: simple-data-backend/
```

2024-03-22 14:37 UTC, evegufy commented on .github/workflows/helm-checks.yaml
> +        context: .
done

2024-04-04 08:27 UTC, ds-jhartmann approved these changes
LGTM

2024-04-04 08:56 UTC, merged