Update umbrella README, add rudimentary Windows section
eclipse-tractusx/tractus-x-umbrella pull request #75
Opened 2024-04-30 11:56 UTC by drandarov-io

## Description

Update umbrella README.md for readability and structure. Add rudimentary differentiation between Linux, Windows and Mac section.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-04-30 12:36 UTC, drandarov-io commented
There seems to be an issue with the recent version bump to 0.11.4

> ✖︎ umbrella => (version: "0.11.4", path: "charts/umbrella") > chart version not ok. Needs a version bump!

2024-05-06 16:57 UTC, drandarov-io commented
### As noted in the Matrix chat:
When running Minikube through Docker for Desktop on Windows, there is an issue with forwarding any requests through the minikube ip.
Alternatively I tried the native Kubernetes Cluster that is included in Docker for Desktop on Windows. Anyone trying to run Minikube on Windows through Docker for Desktop would have access to it as natively as well.
The steps described in the README also natively work with that Cluster. The only addition is installing the nginx-controller:

```
helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace

helm install cert-manager jetstack/cert-manager --namespace umbrella --create-namespace --version v1.14.4 --set installCRDs=true

cd charts/umbrella

kubectl apply -f cluster-issuer.yaml

helm install -f your-values.yaml umbrella . --namespace umbrella
```

The only other change is that Docker for Desktops Kubernetes Cluster uses 127.0.0.1 instead of an independent IP. With this configuration I was able to run the umbrella charts unter Windows.

I'm not sure if using the native Docker for Desktop Cluster an option for you but I thought I'd document it at least.

![image](https://github.com/eclipse-tractusx/tractus-x-umbrella/assets/13102251/2c8a9877-f87c-400b-acf7-519be389abf0)

![image](https://github.com/eclipse-tractusx/tractus-x-umbrella/assets/13102251/53559642-9861-4af1-9301-83cc592dc3ec)

2024-05-14 07:33 UTC, evegufy requested changes
Thanks for the docs PR!
Could you please update (rebase) it to the current state of main and integrate the way you figured out to setup von Windows?

2024-05-14 07:33 UTC, evegufy commented on charts/umbrella/cluster-issuer.yaml
> +apiVersion: cert-manager.io/v1
Could you please add a file header?

2024-05-14 07:36 UTC, drandarov-io commented on charts/umbrella/cluster-issuer.yaml
> +apiVersion: cert-manager.io/v1
Will do

2024-05-15 06:33 UTC, evegufy requested changes

2024-05-15 06:33 UTC, evegufy commented on charts/umbrella/README.md
>  > We plan to test the chart's reliability also on Windows and to update the installation guide accordingly.
Maybe change here: `We are working on testing the chart's reliability...`

2024-05-15 06:33 UTC, evegufy commented on charts/umbrella/README.md
> +#### Linux
Change here to Linux and Mac, as this is also valid for Mac

2024-05-15 06:33 UTC, evegufy commented on charts/umbrella/README.md
> +#### Linux
Change here to Linux and Mac, as this is also valid for Mac

2024-05-15 06:33 UTC, evegufy commented on charts/umbrella/README.md
> +**Additional network setup**
Please call this section Additional network setup for Mac and move it above the Windows section into the Linux and Mac section

2024-05-15 06:33 UTC, evegufy commented on charts/umbrella/README.md
> +If you still face DNS issues afterward, add the hosts to your /etc/hosts file:
Please remove the word afterward, it's not needed or change to afterwards

2024-05-15 06:33 UTC, evegufy commented on charts/umbrella/README.md
> +*Optional:*
remove colon

2024-05-15 06:33 UTC, evegufy commented on charts/umbrella/README.md
> +*Optional:*
remove colon

2024-05-15 18:40 UTC, evegufy approved these changes

2024-05-15 18:41 UTC, merged